/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySideBar: [
    // 'v5/intro',
    'v5/guide',
    {
      type: 'category',
      label: 'WaanX Platform',
      items: [
        'v5/announcement',
        'v5/demo',
        'v5/system-status',
        'v5/smp',
      ]
    },
    {
      type: 'category',
      label: 'Market',
      items: [{ type: 'autogenerated', dirName: 'v5/market' }]
    },
    {
      type: 'category',
      label: 'Trade',
      items: [
        { type: 'autogenerated', dirName: 'v5/order' },
        {
          type: 'category',
          label: 'Bot',
          items: [
            {
              type: 'category',
              label: 'Spot Grid',
              items: [{ type: 'autogenerated', dirName: 'v5/bot/spot-grid' }]
            },
            {
              type: 'category',
              label: 'DCA',
              items: [{ type: 'autogenerated', dirName: 'v5/bot/dca' }]
            },
            'v5/bot/err',
          ]
        },
        {
          type: 'category',
          label: 'Strategy',
          items: [{ type: 'autogenerated', dirName: 'v5/strategy' }]
        }
      ]
    },
    {
      type: 'category',
      label: 'Account',
      items: [{ type: 'autogenerated', dirName: 'v5/account' }]
    },
    {
      type: 'category',
      label: 'Asset',
      items: [
        'v5/asset/fund-history',
        'v5/asset/exchange',
        'v5/asset/coin-info',
        'v5/asset/sub-uid-list',
        'v5/asset/total-members-assets',
        {
          type: 'category',
          label: 'Balances',
          items: [{ type: 'autogenerated', dirName: 'v5/asset/balance' }]
        },
        {
          type: 'category',
          label: 'Transfer',
          items: [{ type: 'autogenerated', dirName: 'v5/asset/transfer' }]
        },
        {
          type: 'category',
          label: 'Deposit',
          items: [{ type: 'autogenerated', dirName: 'v5/asset/deposit' }]
        },
        {
          type: 'category',
          label: 'Withdraw',
          items: [{ type: 'autogenerated', dirName: 'v5/asset/withdraw' }]
        },
        {
          type: 'category',
          label: 'Convert',
          items: [{ type: 'autogenerated', dirName: 'v5/asset/convert' }]
        },
        {
          type: 'category',
          label: 'Convert Small Balances',
          items: [{ type: 'autogenerated', dirName: 'v5/asset/convert-small-balance' }]
        },
        {
          type: 'category',
          label: 'Fiat-Convert',
          items: [{ type: 'autogenerated', dirName: 'v5/asset/fiat-convert' }]
        }
      ]
    },
    {
      type: 'category',
      label: 'User',
      items: [{ type: 'autogenerated', dirName: 'v5/user' }]
    },
    {
      type: 'category',
      label: 'Affiliate',
      items: [{ type: 'autogenerated', dirName: 'v5/affiliate' }]
    },
    {
      type: 'category',
      label: 'Finance',
      items: [
        {
          type: 'category',
          label: 'Earn',
          items: [
            {
              type: 'category',
              label: 'Easy & On-Chain Earn',
              items: [{ type: 'autogenerated', dirName: 'v5/finance/earn/easy-onchain' }]
            },
          ],
        },
      ]
    },
    {
      type: 'category',
      label: 'WebSocket Stream',
      items: [
        'v5/websocket/wss-authentication',
        {
          type: 'category',
          label: 'Public',
          items: [{ type: 'autogenerated', dirName: 'v5/websocket/public' }]
        },
        {
          type: 'category',
          label: 'Private',
          items: [{ type: 'autogenerated', dirName: 'v5/websocket/private' }]
        },
        {
          type: 'category',
          label: 'Trade',
          items: [{ type: 'autogenerated', dirName: 'v5/websocket/trade' }]
        },
        {
          type: 'category',
          label: 'System',
          items: [{ type: 'autogenerated', dirName: 'v5/websocket/system' }]
        },
      ]
    },
    {
      type: 'category',
      label: 'Rate Limit',
      items: [
        'v5/rate-limit/rate-limit',
        'v5/rate-limit/rules-for-vips',
        {
          type: 'category',
          label: 'API Rate Limit Rules for PROs',
          items: [{ type: 'autogenerated', dirName: 'v5/rate-limit/rules-for-pros' }]
        },
      ]
    },
    'v5/enum',
    'v5/error',
  ],
};

module.exports = sidebars;
